### ISSUE TITLE
Performance issue in demo page

### ISSUE THREAD

**Issue by zzarcon** [zzarcon/react-circle#10]
The demo page lags quite a lot when changing the percentage value. Did a small investigation and found that the cause might be the custom FieldRange that we are using.

A possible fix can be to use the native one

**Comment by carstenhag** [comment]
Best practice: Refer to PR # or commit hash when closing an issue :)

**Comment by zzarcon** [comment]
@carstenhag good call! Thats was addressed here https://github.com/zzarcon/react-circle/pull/11 :)
