### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version "^8.4.0". (yarn install)

### ISSUE THREAD

**Issue by JannesMeyer** [zzarcon/react-circle#16]
I'm using node 9.11.1, but your package.json only allows node 8.x

https://github.com/zzarcon/react-circle/blob/57bb4d19df08b739017ce98c3a634ce91da0b596/package.json#L10

**Comment by zzarcon** [comment]
Good one! Do you mind opening a PR with the change? I'd more than happy to merge it 🚀

**Comment by thebarty** [comment]
Please also publish to npm. Right now it seems to be the old version

**Comment by zzarcon** [comment]
@thebarty published in **1.0.3** 🎉

**Comment by thebarty** [comment]
THANKS MAN!!!!! GREAT STUFF! 👍
