### ISSUE TITLE
Percentage over 100 shows as empty.

### ISSUE THREAD

**Issue by karltaylor** [zzarcon/react-circle#35]
When I pass in a percentage greater than 100, it fills in the bgColor, I thought it would just stay 'full'.

I have values that are bigger than 100, My work around is `percent > 100 ? 100 : precent`

**Comment by zzarcon** [comment]
Good catch! I think we should add a fix for that in the **getOffset** method:

```
const getOffset = (val = 0) => Math.round((100 - Math.min(val, 100)) / 100 * diameter);
```

By using **Math.min** in there we will prevent values bigger than 100
